export const gameConfig = {
    mapSize: 15,
    cellSize: 50,
    baseCoord: [
        { x: 8, y: 5 },
        { x: 9, y: 5 },
        { x: 10, y: 5 },
        { x: 11, y: 5 },
        { x: 12, y: 5 },
        { x: 13, y: 5 },
        { x: 8, y: 6 },
        { x: 8, y: 7 },
        { x: 8, y: 8 },
        { x: 8, y: 9 },
        { x: 8, y: 10 },
        { x: 7, y: 11 },
        { x: 8, y: 11 },
        { x: 9, y: 11 },
        { x: 7, y: 12 },
        { x: 9, y: 12 },
        { x: 7, y: 13 },
        { x: 8, y: 13 },
        { x: 9, y: 13 },
    ],
    baseCenter: {
        x: 8,
        y: 12,
    },
    startCell: {
        x: 7,
        y: 13,
    },
};
